#!/usr/bin/env python3

import os
import sys
import logging
import click

logger = logging.getLogger("astroplant_kit")
logger.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
ch.setLevel(logging.getLevelName(os.environ.get('LOG_LEVEL', 'DEBUG')))

formatter = logging.Formatter(
    '%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s'
)

ch.setFormatter(formatter)
logger.addHandler(ch)


@click.group()
def cli():
    pass


@cli.command()
def version():
    import astroplant_kit
    print(astroplant_kit.__version__)


@cli.command()
@click.argument('config-file', type=click.File('r'), default="./kit_config.toml")
@click.option('--cache-dir', type=click.Path(exists=False, dir_okay=True, file_okay=False, writable=True, readable=True, resolve_path=True), default="./cache")
def run(config_file, cache_dir):
    """
    Run the AstroPlant kit.

    CONFIG_FILE is the configuration file to be used, defaulting to `./kit_config.toml`.
    """
    import trio

    import astroplant_kit.config
    from astroplant_kit.api import Client
    from astroplant_kit.cache import Cache
    from astroplant_kit.kit import Kit
    from astroplant_kit.kit_rpc import KitRpc

    logger.info('Reading configuration.')
    try:
        conf = astroplant_kit.config.read_config(config_file)
    except Exception as e:
        logger.error('Exception while reading configuration: %s' % e)
        sys.exit(e.errno)

    logger.info('Creating AstroPlant network client.')

    api_client = Client(**conf["message_broker"])

    cache = Cache(cache_dir)

    logger.info('Initialising kit.')
    kit = Kit(api_client, conf["debug"], cache)

    kit_rpc = KitRpc(kit)

    api_client.register_kit_rpc_handler(kit_rpc)

    async def run():
        async with trio.open_nursery() as nursery:
            nursery.start_soon(api_client.run)
            nursery.start_soon(kit.run)

    trio.run(run)

if __name__ == "__main__":
    cli()
