[message_broker]
host = "mqtt.astroplant.io"
port = 1883

[message_broker.auth]
serial = "<INSERT KIT SERIAL HERE>"
secret = "<INSERT KIT SECRET HERE>"

[debug]
level = "INFO"

[debug.peripheral_display]
module_name = "peripheral"
class_name = "BlackHoleDisplay"
