[api]
root = "https://my.astroplant.io/api/"

[websockets]
url = "wss://my.astroplant.io/"

[auth]
serial = "<INSERT KIT SERIAL HERE>"
secret = "<INSERT KIT SECRET HERE>"

[debug]
level = "INFO"

[debug.peripheral_display]
module_name = "peripheral"
class_name = "BlackHoleDisplay"
