[api]
root = "https://my.astroplant.io/api/"

[websockets]
url = "wss://my.astroplant.io/"

[auth]
serial = "k.8yxx78qp"
secret = "DRWcNkQmw9rR#rb6ry9K#Bfm"

[debug]
level = "INFO"

[debug.peripheral_display]
module_name = "peripheral"
class_name = "DebugDisplay"
